[tox]
envlist = format, py36, py37, py38, pylint, mypy
skip_missing_interpreters = true

[testenv]
deps =
    pytest
    pytest-cov
commands =
    py.test --basetemp={envtmpdir} -vv \
        --cov=pyBusPirateLite --cov-report=html --cov-report=term-missing


[testenv:format]
skip_install = true
deps =
    black
    isort
    autoflake
commands =
    autoflake --in-place --remove-all-unused-imports --expand-star-imports \
        --ignore-init-module-imports --recursive pyBusPirateLite
    isort -rc {toxinidir}
    black {toxinidir}

[testenv:pylint]
deps =
    pylint
commands = pylint pyBusPirateLite

[testenv:mypy]
setenv =
    MYPYPATH = {toxinidir}
deps = mypy
commands = mypy -p pyBusPirateLite  --ignore-missing-imports
